%%writefile /content/stackoverflow_custom/dbt_project.yml
name: stack_overflow_insights
version: '1.0'
config-version: 2

profile: stack_overflow_insights

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

