stack_overflow_insights:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json # <--- ZMIEŃ NA TĘ METODĘ
      keyfile: /sciezka/do/pobranego/dbt-runner-12345.json # <--- WSTAWIJ BEZWZGLĘDNĄ ŚCIEŻKĘ
      project: polar-gasket-477509-q6 
      dataset: stackoverflow_custom # lub inny docelowy schemat
      threads: 4
      location: US
