name: dbt Continuous Integration

on:
  push:
    branches:
      - main # Uruchom przy każdym pushu do gałęzi main
  pull_request:
    branches:
      - main # Uruchom przy każdym nowym Pull Request

jobs:
  dbt_build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Konfiguracja środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 2. Instalacja zależności dbt
      - name: Install dbt-bigquery
        run: pip install dbt-bigquery

      - name: Install dbt packages
        run: dbt deps

      # 3. Konfiguracja uwierzytelniania GCP i profiles.yml
      # Wstrzyknięcie klucza JSON konta serwisowego do pliku tymczasowego
      - name: Authorize GCP Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} 
          
      # 4. Utworzenie profiles.yml na podstawie zmiennych środowiskowych i klucza
      - name: Create profiles.yml for CI/CD
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
stackoverflow_insights:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account-json
      project: polar-gasket-477509-q6 
      # Używa tymczasowej zmiennej z Google Auth Action (GCP_SA_KEY_FILE)
      keyfile: ${{ steps.auth.outputs.credentials_file_path }}
      dataset: stackoverflow_custom 
      threads: 4
      location: US
      priority: interactive
EOF
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 5. Uruchomienie budowania modelu i testów
      - name: Run dbt build (Transformation and Tests)
        run: dbt build --profile stackoverflow_insights --target ci
